
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PORT: 3000
  MONGODB_URL: mongodb://127.0.0.1:27017/node-ts-boilerplate
  JWT_SECRET: thisisasamplesecret
  JWT_ACCESS_EXPIRATION_MINUTES: 30
  JWT_REFRESH_EXPIRATION_DAYS: 30
  JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10
  JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10

jobs:
  run-linting-tests:

    runs-on: ubuntu-latest

    uses: ./.github/workflows/setUp.yml

    steps:
    - name: Run linting tests
      run: yarn lint

  run-unit-tests:

    runs-on: ubuntu-latest

    uses: ./.github/workflows/setUp.yml

    steps:
    - name: Run unit tests
      run: yarn test

  generate-coverage:

    runs-on: ubuntu-latest

    needs: run-unit-tests

    uses: ./.github/workflows/setUp.yml

    steps:
    - name: Generate coverage
      run: yarn coverage:coveralls
